-- CONSULTA 1
SELECT P.NOMBRE AS Proyecto, PR.PRODUCTO
FROM PROYECTO P
JOIN PRODUCTO_PROYECTO PP ON P.COD_PROYECTO = PP.PROYECTO
JOIN PRODUCTO PR ON PP.PRODUCTO = PR.PRODUCTO
WHERE P.COD_PROYECTO = 1;

-- CONSULTA 2 
SELECT M.COD_MENSAJE, P.NOMBRE AS Proyecto, PR.PRODUCTO, F.NOMBRE AS Formato, F.REMITENTE, F.ASUNTO
FROM MENSAJE M
JOIN PROYECTO P ON M.PROYECTO = P.COD_PROYECTO
JOIN PRODUCTO PR ON M.PRODUCTO = PR.PRODUCTO
JOIN FORMATO_MENSAJE F ON M.COD_TIPO = F.COD_TIPO AND M.COD_TIPO_INFORMACION = F.COD_TIPO_INFORMACION;

-- CONSULTA 3
SELECT 
    P.NOMBRE AS Proyecto,
    CASE 
        WHEN COUNT(DISTINCT PR.PRODUCTO) = (SELECT COUNT(*) FROM PRODUCTO_PROYECTO PP2 WHERE PP2.PROYECTO = P.COD_PROYECTO)
        THEN 'TODOS'
        ELSE PR.PRODUCTO
    END AS Producto,
    M.COD_MENSAJE, 
    F.NOMBRE AS Formato, 
    F.REMITENTE, 
    F.ASUNTO
FROM MENSAJE M
JOIN PROYECTO P ON M.PROYECTO = P.COD_PROYECTO
JOIN PRODUCTO PR ON M.PRODUCTO = PR.PRODUCTO
JOIN FORMATO_MENSAJE F ON M.COD_TIPO = F.COD_TIPO AND M.COD_TIPO_INFORMACION = F.COD_TIPO_INFORMACION
GROUP BY P.NOMBRE, M.COD_MENSAJE, F.NOMBRE, F.REMITENTE, F.ASUNTO, P.COD_PROYECTO, PR.PRODUCTO
HAVING COUNT(DISTINCT PR.PRODUCTO) = (SELECT COUNT(*) FROM PRODUCTO_PROYECTO PP2 WHERE PP2.PROYECTO = P.COD_PROYECTO)
    OR COUNT(DISTINCT PR.PRODUCTO) < (SELECT COUNT(*) FROM PRODUCTO_PROYECTO PP2 WHERE PP2.PROYECTO = P.COD_PROYECTO);
